export enum MEETING_TYPES_ENUM {
  budgeting = 'budgeting',
  checking_and_saving = 'checking_and_saving',
  debt_management = 'debt_management',
  managing_credit_cards = 'managing_credit_cards',
  investing = 'investing',
  managing_student_loans = 'managing_student_loans',
  credit_unions = 'credit_unions',
  first_time_home_buyer = 'first_time_home_buyer',
  starting_small_business = 'starting_small_business',
  create_passive_income = 'create_passive_income',
  credit_reports_and_tips = 'credit_reports_and_tips',
  preparing_for_retirement = 'preparing_for_retirement',
  trust_and_estate_services = 'trust_and_estate_services',
  escroe_services = 'escroe_services',
  online_and_mobile_banking = 'online_and_mobile_banking',
  money_market_accounts = 'money_market_accounts',
  certificate_of_deposits = 'certificate_of_deposits',
  home_equity_loans = 'home_equity_loans',
  auto_loans = 'auto_loans',
  personal_loans = 'personal_loans',
}
